export enum ConfigEnum {
  NSET_SERVER_PORT = "NSET_SERVER_PORT",
  MYSQL_SERVER_HOST = "MYSQL_SERVER_HOST",
  MYSQL_SERVER_PORT = "MYSQL_SERVER_PORT",

  MYSQL_SERVER_USERNAME = "MYSQL_SERVER_USERNAME",
  MYSQL_SERVER_PASSWORD = "MYSQL_SERVER_PASSWORD",
  MYSQL_SERVER_DATABASE = "MYSQL_SERVER_DATABASE",

  REDIS_SERVER_HOST = "REDIS_SERVER_HOST",
  REDIS_SERVER_PORT = "REDIS_SERVER_PORT",
  REDIS_SERVER_DB = "REDIS_SERVER_DB",
  REDIS_USERNAME = "REDIS_USERNAME",
  REDIS_PASSWORD = "REDIS_PASSWORD",

  JWT_SECRET = "JWT_SECRET",
  JWT_ACCESS_TOKEN_EXPIRES_TIME = "JWT_ACCESS_TOKEN_EXPIRES_TIME",
  JWT_REFRESH_TOKEN_EXPIRES_TIME = "JWT_REFRESH_TOKEN_EXPIRES_TIME",

  LOG_ON = "LOG_ON",

  SWAGGER_ENABLE = "SWAGGER_ENABLE",

  REDIS_REGISTER_CODE = "REDIS_REGISTER_CODE",
}
