NSET:
  PORT: 3005

MYSQL:
  DATABASE: accounting
  PORT: 3306
  HOST: 127.0.0.1
  USERNAME: root
  PASSWORD: "123456"
  LOG_ON: false

REDIS:
  HOST: 127.0.0.1
  PORT: 6379
  DB: 0
  REGISTER_CODE : registerCode
JWT:
  SECRET: tang
  ACCESS_TOKEN_EXPIRES_TIME: 7d
  REFRESH_TOKEN_EXPIRES_TIME: 7d

LOG:
  ON: true

SWAGGER_ENABLE: true