
MYSQL:
  DATABASE: accounting
  PORT: 3306
  HOST: mysql-container
  USERNAME: root
  PASSWORD: "123456"
  LOG_ON: false

REDIS:
  HOST: redis-container
  PORT: 6379
  DB: 0
  REGISTER_CODE : registerCode

JWT:
  SECRET: tang
  ACCESS_TOKEN_EXPIRES_TIME: 7d
  REFRESH_TOKEN_EXPIRES_TIME: 7d

LOG:
  ON: true

SWAGGER_ENABLE: true